name: Testing stuff

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: messages contain skip
        if: ${{ contains(join(toJson(github.event.commits.*.message)), '#skip') }}
        env:
          COMMIT_MESSAGES: ${{ contains(join(toJson(github.event.commits.*.message)), '#skip') }}
        run: echo "$COMMIT_MESSAGES"
